## 实验题目5 高斯(Gauss)列主元消去法

In [67]:
using Printf
using LinearAlgebra

In [68]:
# from: https://stackoverflow.com/questions/58667332/is-there-a-way-to-swap-columns-in-o1-in-julia
function swapcols!(X::AbstractMatrix, i::Integer, j::Integer)
    @inbounds for k = 1:size(X,1)
        X[k,i], X[k,j] = X[k,j], X[k,i]
    end
end
# from: https://discourse.julialang.org/t/swap-cols-rows-of-a-matrix/47904/9
function _swapcol!(x,i,j)
    for k in axes(x, 1)  # <- give dimension as input to axes function
        x[k, i], x[k, j] = x[k, j], x[k, i]
    end
end

_swapcol! (generic function with 1 method)

In [69]:
    function swaprows!(X::AbstractMatrix, i::Integer, j::Integer)
        @inbounds for k = 1:size(X,2)
            X[i,k], X[j,k] = X[j,k], X[i,k]
        end
    end

swaprows! (generic function with 1 method)

In [70]:
# Gauss列主元消去法
# Todo: modify it using . operator
##
# 1.0  2.0  3.0  0.123
# 2.0  4.0  5.0  0.834
# 3.0  5.0  6.0  0.348
##
function gauss(n, A::Matrix{Float64}, b::Vector{Float64})
    for k = 1:n-1
        val, idx = findmax(A[k:n, k])
        idx += k - 1
        # val, idx = findmax(A[:, k]) # hey, see here, that caused error
        display("val=$val, idx=$idx")
        if val == 0
            @printf("Cannot solve a singular matrix!")
            return
        end
        if idx != k
            swaprows!(A, idx, k)
            b[idx], b[k] = b[k], b[idx]
        end
        display("after swaprows:")
        display([A b])
        for i = k+1:n
            m = A[i, k] / A[k, k]
            A[i, :] -= A[k, :] * m
            b[i] -= b[k] * m
        end
        display("after elimination:")
        display([A b])
    end
    display([A b])
    if A[n, n] == 0
        @printf("Cannot solve a singular matrix!")
    end
    # https://stackoverflow.com/questions/62142717/julia-quick-way-to-initialise-an-empty-array-thats-the-same-size-as-another
    x = similar(b, Float64)
    # println(b)
    x[n] = b[n] / A[n, n]
    for k = n-1:1
        x[k] = (b[k] - A[k, k+1:n] * x[k+1:n]) / A[k, k]
    end
    display(x)
end


gauss (generic function with 1 method)

In [71]:
A = [1 2 3;2 4 5;3 5.0 6]
b = [0.123; 0.834; 0.348]
A\b

3-element Vector{Float64}:
 -1.6829999999999983
  1.784999999999999
 -0.588

In [72]:
display([A b])
gauss(3,A,b)

3×4 Matrix{Float64}:
 1.0  2.0  3.0  0.123
 2.0  4.0  5.0  0.834
 3.0  5.0  6.0  0.348

"val=3.0, idx=3"

"after swaprows:"

3×4 Matrix{Float64}:
 3.0  5.0  6.0  0.348
 2.0  4.0  5.0  0.834
 1.0  2.0  3.0  0.123

"after elimination:"

3×4 Matrix{Float64}:
 3.0  5.0       6.0  0.348
 0.0  0.666667  1.0  0.602
 0.0  0.333333  1.0  0.007

"val=0.666666666666667, idx=2"

"after swaprows:"

3×4 Matrix{Float64}:
 3.0  5.0       6.0  0.348
 0.0  0.666667  1.0  0.602
 0.0  0.333333  1.0  0.007

"after elimination:"

3×4 Matrix{Float64}:
 3.0  5.0       6.0   0.348
 0.0  0.666667  1.0   0.602
 0.0  0.0       0.5  -0.294

3×4 Matrix{Float64}:
 3.0  5.0       6.0   0.348
 0.0  0.666667  1.0   0.602
 0.0  0.0       0.5  -0.294

3-element Vector{Float64}:
  9.0532233e-316
  9.0548162e-316
 -0.588